# Group Disciplines
Welcome to the disciplines API. This API provides access to the disciplines service.

## disciplines [/disciplines]

### Create discipline [POST]

Create a new discipline

+ Request discipline (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json
    + Attributes

        + name: NAME (string)
        + description: DESCRIPTION (string)
        + segment: SEGMENT (string)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (discipline, fixed)

### Get disciplines [GET]

Returns a discipline list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (discipline)

## discipline details [/disciplines/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired discipline.
        + Members
            + `1`
            + `2`
            + `3`

### Get discipline [GET]

Returns a discipline.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (discipline, fixed)

### Update discipline [PUT]

Update a discipline.

+ Request discipline (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json
    + Attributes

        + name: NAME (string)
        + description: DESCRIPTION (string)
        + segment: SEGMENT (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (discipline, fixed)

### Delete discipline [DELETE]

Delete a discipline.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 204

# Data Structures
## discipline (object)

+ id: *1* (number)
+ name: *NAME* (string)
+ description: *DESCRIPTION* (string)
+ segment: *SEGMENT* (string)
+ createdAt: `*2000-01-01 00:00:00*` (string)
+ updatedAt: `*2000-01-01 00:00:00*` (string)
