FORMAT: 1A
HOST: http://localhost:8080

# Escolando API

<!-- include(class.apib) -->
<!-- include(discipline.apib) -->
<!-- include(in_charge.apib) -->
<!-- include(in_charge_role.apib) -->
<!-- include(institution.apib) -->
<!-- include(kinship.apib) -->
<!-- include(parent.apib) -->
<!-- include(parent_student.apib) -->
<!-- include(register.apib) -->
<!-- include(register_current_status.apib) -->
<!-- include(register_status.apib) -->
<!-- include(register_type.apib) -->
<!-- include(school_grade.apib) -->
<!-- include(student.apib) -->
<!-- include(student_enrollment.apib) -->
<!-- include(teacher_class.apib) -->
<!-- include(user.apib) -->
<!-- include(user_access.apib) -->
<!-- include(user_access_profile.apib) -->
