# Group Segments
Welcome to the segments API. This API provides access to the segments service.

## segments [/segments]

### Create segment [POST]

Create a new segment

+ Request segment (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json
    + Attributes

        +  (institution)
        + name: NAME (string)
        + description: DESCRIPTION (string)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (segment, fixed)

### Get segments [GET]

Returns a segment list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (segment)

## segment details [/segments/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired segment.
        + Members
            + `1`
            + `2`
            + `3`

### Get segment [GET]

Returns a segment.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (segment, fixed)

### Update segment [PUT]

Update a segment.

+ Request segment (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json
    + Attributes

        +  (institution)
        + name: NAME (string)
        + description: DESCRIPTION (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (segment, fixed)

### Delete segment [DELETE]

Delete a segment.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 204

# Data Structures
## segment (object)

+ id: *1* (number)
+  (institution)
+ name: *NAME* (string)
+ description: *DESCRIPTION* (string)
+ createdAt: `*2000-01-01 00:00:00*` (string)
+ updatedAt: `*2000-01-01 00:00:00*` (string)
