# Group StudentEnrollments
Welcome to the student enrollments API. This API provides access to the student enrollments service.

## student enrollments [/student_enrollments]

### Create student enrollment [POST]

Create a new student enrollment

+ Request student enrollment (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json
    + Attributes

        + student (student)
        + StudentID: 1 (number)
        + class (class)
        + ClassID: 1 (number)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (student_enrollment, fixed)

### Get student enrollments [GET]

Returns a student enrollment list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (student_enrollment)

## student enrollment details [/student_enrollments/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired student enrollment.
        + Members
            + `1`
            + `2`
            + `3`

### Get student enrollment [GET]

Returns a student enrollment.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (student_enrollment, fixed)

### Update student enrollment [PUT]

Update a student enrollment.

+ Request student_enrollment (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json
    + Attributes

        + student (student)
        + StudentID: 1 (number)
        + class (class)
        + ClassID: 1 (number)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (student_enrollment, fixed)

### Delete student enrollment [DELETE]

Delete a student enrollment.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 204

# Data Structures
## student_enrollment (object)

+ id: *1* (number)
+ student (student)
+ StudentID: *1* (number)
+ class (class)
+ ClassID: *1* (number)
+ createdAt: `*2000-01-01 00:00:00*` (string)
+ updatedAt: `*2000-01-01 00:00:00*` (string)
