# Group TeacherClasses
Welcome to the teacher classes API. This API provides access to the teacher classes service.

## teacher classes [/teacher_classes]

### Create teacher class [POST]

Create a new teacher class

+ Request teacher class (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json
    + Attributes

        + teacher (incharge)
        + discipline (discipline)
        + class (class)
        + week_day: WEEKDAY (string)
        + start_hour: 1 (number)
        + start_minutes: 1 (number)
        + end_hour: 1 (number)
        + en_minutes: 1 (number)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (teacher_class, fixed)

### Get teacher classes [GET]

Returns a teacher class list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (teacher_class)

## teacher class details [/teacher_classes/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired teacher class.
        + Members
            + `1`
            + `2`
            + `3`

### Get teacher class [GET]

Returns a teacher class.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (teacher_class, fixed)

### Update teacher class [PUT]

Update a teacher class.

+ Request teacher_class (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json
    + Attributes

        + teacher (incharge)
        + discipline (discipline)
        + class (class)
        + week_day: WEEKDAY (string)
        + start_hour: 1 (number)
        + start_minutes: 1 (number)
        + end_hour: 1 (number)
        + en_minutes: 1 (number)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (teacher_class, fixed)

### Delete teacher class [DELETE]

Delete a teacher class.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 204

# Data Structures
## teacher_class (object)

+ id: *1* (number)
+ teacher (incharge)
+ discipline (discipline)
+ class (class)
+ week_day: *WEEKDAY* (string)
+ start_hour: *1* (number)
+ start_minutes: *1* (number)
+ end_hour: *1* (number)
+ en_minutes: *1* (number)
+ created_at: `*2000-01-01 00:00:00*` (string)
+ updated_at: `*2000-01-01 00:00:00*` (string)
